[package]
name = "proxmox-api"
version = "0.1.0"
edition = "2021"

[features]
default = [ "access", "cluster", "nodes", "pools", "storage", "version" ]
access = []
cluster = []
nodes = []
pools = []
storage = []
version = []
reqwest = [ "dep:reqwest" ]
cli = [ "dep:clap", "dep:pretty_env_logger", "reqwest" ]

[[bin]]
name = "proxmox-api"
path = "./src/cli/main.rs"
required-features = [ "cli" ]

[package.metadata.proxmox]
debian-distro = "bookworm"
pve-version = "8.0.1"

[dependencies]
log = "0.4.21"
parking_lot = "0.12.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_urlencoded = "0.7.1"

# CLI deps
reqwest = { optional = true, version = "0.12.1", features = ["blocking", "json"] }
clap = { optional = true, version = "4.5.3", features = ["derive", "env"] }
pretty_env_logger = { optional = true, version = "0.5.0" }
