name: Validate that generated methods
run-name: Generating JSON definitions for Proxmox
on: [push]
env:
  CONTAINER_NAME: json-container
jobs:
  create:
    runs-on: ubuntu-latest
    # container: debian:bookworm
    name: "Generate JSON definitions"
    steps:
      - uses: actions/checkout@v4

      - name: Create container
        run: |
          docker run --mount "type=bind,source=./ci,target=/mnt" --name $CONTAINER_NAME debian:bookworm

      - name: Setup proxmox bookworm
        run: docker exec -it $CONTAINER_NAME /mnt/setup.sh

      - name: Generate JSON schema
        run: docker exec -it $CONTAINER_NAME /mnt/dump-schema.pl > PVE-schema.json

      - name: Show line count
        run: wc -l ./ci/PVE-schema.json

      # - name: Save all package versions to a file
      #   run: |
      #     apt list --installed > packages.txt

      - name: Upload the generated JSON
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ./ci/PVE-schema.json
