name: Generating JSON definitions for Proxmox
run-name: Generating JSON definitions for Proxmox
on: [push]
jobs:
  create:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Set up proxmox bookworm
        run: ./ci/setup.sh

      - name: Generate JSON schema
        run: ./ci/dump-schema.pl > PVE-schema.json

      - name: Show line count
        run: wc -l PVE-schema.json

      - name: Save all package versions to a file
        run: |
          apt list --installed > packages.txt

      - name: Upload the generated JSON
        uses: actions/upload-artifact@v4
        with:
          name: PVE-schema.json
          path: |
            ./PVE-schema.json
            ./packages.txt